@extends("theme.$theme.layout")
@section('encabezado')
    @include("admin/admin/headeradmin")
@endsection
@section('lateral')
    @include("admin/admin/aside")
@endsection
@section('contenido')
    @include('mensajes.exito')
    @include('admin.admin.historico')
    @include('admin.admin.grafico')
    @include('admin.admin.tabladatos')
    @include('admin.admin.test')
@endsection
